language: node_js
node_js:
- 11.10.1
cache: yarn

before_script :
 - curl -o- -L https://yarnpkg.com/install.sh | bash -s
 - export PATH=$HOME/.yarn/bin:$PATH
 - yarn install

script:
  - yarn run build

deploy:
  provider: heroku
  api_key:
    secure: gsVPhhuefFAjt3VhaSjVLEjHYSBqZKpsgDtbR+frunOgqkXKI+qO47cafHUrw0OSMehqkD2nzJPFIXazG46+g+gv1UJck9dxUUNo6tIBLiHARfGNWKuXhax5ENZfdxcSuJqZuCG3HlQrCtyLfBjWxvsfFZN9kJYoJeAXDnmou0Nn9jqdwCt8eOXMJhF01RXlojY20DRKTHZf7kj/f7o5aVFM084qvAFsFnciLHla/pBfg1ifYI4kyCN2WVuiShUfFt7S+MthWYfT4ef3mb84quLs5fU9gXqAuTCf5w/eRpTW6j2brpvvS4D+6CjQ5fDnHhlXo/2vKttg3T2mjSlBjCO3sB2LUoPWZUVy5k/cWaYbNnWvmZKYwcl7TGrDR17IBXtUlj76G0z/ksk132cK6enEvTc+AVcVFJLaTJuGHBaWXpv5ZThoDkqQ27T1l7Tr7MPaDA07YUR7CBtg4o9Orpc123bwAYQMoajy1v5LhG05eVpbF7qLwsP+0rrKOiOa3c53RD9Dz/S3x0KmWE/p6Ek5Hln8y1NzIFZdJfW2/EYS80mofxq+cke91Q3FVYtLcuGSUGGU9QtAQn9MFC9GQ0oK86DdDWnsIB4Llu5TuIQ7U4wtwVHuY9elIZqGYz39I9hALFCn8ahKG+o6vOtWLkh+A5MwUaB2KMs3nb5APsA=
  app:
   react-hn-clone